// Generated by Haxe 3.4.4
#include <hxcpp.h>

#ifndef INCLUDED_armory_logicnode_GoToLocationNode
#include <armory/logicnode/GoToLocationNode.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicNode
#include <armory/logicnode/LogicNode.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicNodeInput
#include <armory/logicnode/LogicNodeInput.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicTree
#include <armory/logicnode/LogicTree.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <iron/Trait.h>
#endif
#ifndef INCLUDED_iron_math_Vec4
#include <iron/math/Vec4.h>
#endif
#ifndef INCLUDED_iron_object_Object
#include <iron/object/Object.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_a22a13d456645451_10_new,"armory.logicnode.GoToLocationNode","new",0x52bf84ee,"armory.logicnode.GoToLocationNode.new","armory/logicnode/GoToLocationNode.hx",10,0x1bbbd840)
HX_LOCAL_STACK_FRAME(_hx_pos_a22a13d456645451_13_run,"armory.logicnode.GoToLocationNode","run",0x52c29bd9,"armory.logicnode.GoToLocationNode.run","armory/logicnode/GoToLocationNode.hx",13,0x1bbbd840)
namespace armory{
namespace logicnode{

void GoToLocationNode_obj::__construct( ::armory::logicnode::LogicTree tree){
            	HX_STACKFRAME(&_hx_pos_a22a13d456645451_10_new)
HXDLIN(  10)		super::__construct(tree);
            	}

Dynamic GoToLocationNode_obj::__CreateEmpty() { return new GoToLocationNode_obj; }

void *GoToLocationNode_obj::_hx_vtable = 0;

Dynamic GoToLocationNode_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< GoToLocationNode_obj > _hx_result = new GoToLocationNode_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool GoToLocationNode_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x06b89e60) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x06b89e60;
	} else {
		return inClassId==(int)0x2e933162;
	}
}

void GoToLocationNode_obj::run(){
            	HX_STACKFRAME(&_hx_pos_a22a13d456645451_13_run)
HXLINE(  14)		 ::iron::object::Object object = ( ( ::iron::object::Object)(this->inputs->__get((int)1).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  15)		 ::iron::math::Vec4 location = ( ( ::iron::math::Vec4)(this->inputs->__get((int)2).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  17)		if (hx::IsNull( location )) {
HXLINE(  17)			return;
            		}
HXLINE(  18)		if (hx::IsNull( object )) {
HXLINE(  18)			return;
            		}
HXLINE(  30)		this->super::run();
            	}



hx::ObjectPtr< GoToLocationNode_obj > GoToLocationNode_obj::__new( ::armory::logicnode::LogicTree tree) {
	hx::ObjectPtr< GoToLocationNode_obj > __this = new GoToLocationNode_obj();
	__this->__construct(tree);
	return __this;
}

hx::ObjectPtr< GoToLocationNode_obj > GoToLocationNode_obj::__alloc(hx::Ctx *_hx_ctx, ::armory::logicnode::LogicTree tree) {
	GoToLocationNode_obj *__this = (GoToLocationNode_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(GoToLocationNode_obj), true, "armory.logicnode.GoToLocationNode"));
	*(void **)__this = GoToLocationNode_obj::_hx_vtable;
	__this->__construct(tree);
	return __this;
}

GoToLocationNode_obj::GoToLocationNode_obj()
{
}

hx::Val GoToLocationNode_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { return hx::Val( run_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *GoToLocationNode_obj_sMemberStorageInfo = 0;
static hx::StaticInfo *GoToLocationNode_obj_sStaticStorageInfo = 0;
#endif

static ::String GoToLocationNode_obj_sMemberFields[] = {
	HX_HCSTRING("run","\x4b","\xe7","\x56","\x00"),
	::String(null()) };

static void GoToLocationNode_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(GoToLocationNode_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void GoToLocationNode_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(GoToLocationNode_obj::__mClass,"__mClass");
};

#endif

hx::Class GoToLocationNode_obj::__mClass;

void GoToLocationNode_obj::__register()
{
	hx::Object *dummy = new GoToLocationNode_obj;
	GoToLocationNode_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("armory.logicnode.GoToLocationNode","\xfc","\x35","\xcb","\x1c");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = GoToLocationNode_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(GoToLocationNode_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< GoToLocationNode_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = GoToLocationNode_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = GoToLocationNode_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = GoToLocationNode_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace armory
} // end namespace logicnode
