// Generated by Haxe 3.4.4
#include <hxcpp.h>

#ifndef INCLUDED_armory_logicnode_LogicNode
#include <armory/logicnode/LogicNode.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicTree
#include <armory/logicnode/LogicTree.h>
#endif
#ifndef INCLUDED_armory_logicnode_SensorCoordsNode
#include <armory/logicnode/SensorCoordsNode.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <iron/Trait.h>
#endif
#ifndef INCLUDED_iron_math_Vec4
#include <iron/math/Vec4.h>
#endif
#ifndef INCLUDED_iron_system_Input
#include <iron/system/Input.h>
#endif
#ifndef INCLUDED_iron_system_Sensor
#include <iron/system/Sensor.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_2f6f425af1d236a2_5_new,"armory.logicnode.SensorCoordsNode","new",0x66e773ce,"armory.logicnode.SensorCoordsNode.new","armory/logicnode/SensorCoordsNode.hx",5,0xdcaf6560)
HX_LOCAL_STACK_FRAME(_hx_pos_2f6f425af1d236a2_13_get,"armory.logicnode.SensorCoordsNode","get",0x66e22404,"armory.logicnode.SensorCoordsNode.get","armory/logicnode/SensorCoordsNode.hx",13,0xdcaf6560)
namespace armory{
namespace logicnode{

void SensorCoordsNode_obj::__construct( ::armory::logicnode::LogicTree tree){
            	HX_GC_STACKFRAME(&_hx_pos_2f6f425af1d236a2_5_new)
HXLINE(   7)		this->coords =  ::iron::math::Vec4_obj::__alloc( HX_CTX ,null(),null(),null(),null());
HXLINE(  10)		super::__construct(tree);
            	}

Dynamic SensorCoordsNode_obj::__CreateEmpty() { return new SensorCoordsNode_obj; }

void *SensorCoordsNode_obj::_hx_vtable = 0;

Dynamic SensorCoordsNode_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< SensorCoordsNode_obj > _hx_result = new SensorCoordsNode_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool SensorCoordsNode_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x2e933162) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x2e933162;
	} else {
		return inClassId==(int)0x3ac79d40;
	}
}

 ::Dynamic SensorCoordsNode_obj::get(int from){
            	HX_STACKFRAME(&_hx_pos_2f6f425af1d236a2_13_get)
HXLINE(  14)		 ::iron::_hx_system::Sensor sensor = ::iron::_hx_system::Input_obj::getSensor();
HXLINE(  15)		this->coords->x = sensor->x;
HXLINE(  16)		this->coords->y = sensor->y;
HXLINE(  17)		this->coords->z = sensor->z;
HXLINE(  18)		return this->coords;
            	}



hx::ObjectPtr< SensorCoordsNode_obj > SensorCoordsNode_obj::__new( ::armory::logicnode::LogicTree tree) {
	hx::ObjectPtr< SensorCoordsNode_obj > __this = new SensorCoordsNode_obj();
	__this->__construct(tree);
	return __this;
}

hx::ObjectPtr< SensorCoordsNode_obj > SensorCoordsNode_obj::__alloc(hx::Ctx *_hx_ctx, ::armory::logicnode::LogicTree tree) {
	SensorCoordsNode_obj *__this = (SensorCoordsNode_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(SensorCoordsNode_obj), true, "armory.logicnode.SensorCoordsNode"));
	*(void **)__this = SensorCoordsNode_obj::_hx_vtable;
	__this->__construct(tree);
	return __this;
}

SensorCoordsNode_obj::SensorCoordsNode_obj()
{
}

void SensorCoordsNode_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(SensorCoordsNode);
	HX_MARK_MEMBER_NAME(coords,"coords");
	 ::armory::logicnode::LogicNode_obj::__Mark(HX_MARK_ARG);
	HX_MARK_END_CLASS();
}

void SensorCoordsNode_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(coords,"coords");
	 ::armory::logicnode::LogicNode_obj::__Visit(HX_VISIT_ARG);
}

hx::Val SensorCoordsNode_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { return hx::Val( get_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"coords") ) { return hx::Val( coords ); }
	}
	return super::__Field(inName,inCallProp);
}

hx::Val SensorCoordsNode_obj::__SetField(const ::String &inName,const hx::Val &inValue,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"coords") ) { coords=inValue.Cast<  ::iron::math::Vec4 >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void SensorCoordsNode_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_HCSTRING("coords","\x1e","\xa4","\x84","\xc8"));
	super::__GetFields(outFields);
};

#if HXCPP_SCRIPTABLE
static hx::StorageInfo SensorCoordsNode_obj_sMemberStorageInfo[] = {
	{hx::fsObject /*::iron::math::Vec4*/ ,(int)offsetof(SensorCoordsNode_obj,coords),HX_HCSTRING("coords","\x1e","\xa4","\x84","\xc8")},
	{ hx::fsUnknown, 0, null()}
};
static hx::StaticInfo *SensorCoordsNode_obj_sStaticStorageInfo = 0;
#endif

static ::String SensorCoordsNode_obj_sMemberFields[] = {
	HX_HCSTRING("coords","\x1e","\xa4","\x84","\xc8"),
	HX_HCSTRING("get","\x96","\x80","\x4e","\x00"),
	::String(null()) };

static void SensorCoordsNode_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(SensorCoordsNode_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void SensorCoordsNode_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(SensorCoordsNode_obj::__mClass,"__mClass");
};

#endif

hx::Class SensorCoordsNode_obj::__mClass;

void SensorCoordsNode_obj::__register()
{
	hx::Object *dummy = new SensorCoordsNode_obj;
	SensorCoordsNode_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("armory.logicnode.SensorCoordsNode","\xdc","\x34","\xda","\x50");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = SensorCoordsNode_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(SensorCoordsNode_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< SensorCoordsNode_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = SensorCoordsNode_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = SensorCoordsNode_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = SensorCoordsNode_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace armory
} // end namespace logicnode
