// Generated by Haxe 3.4.4
#include <hxcpp.h>

#ifndef INCLUDED_armory_logicnode_LogicNode
#include <armory/logicnode/LogicNode.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicNodeInput
#include <armory/logicnode/LogicNodeInput.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicTree
#include <armory/logicnode/LogicTree.h>
#endif
#ifndef INCLUDED_armory_logicnode_SetCameraFovNode
#include <armory/logicnode/SetCameraFovNode.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <iron/Trait.h>
#endif
#ifndef INCLUDED_iron_data_CameraData
#include <iron/data/CameraData.h>
#endif
#ifndef INCLUDED_iron_data_Data
#include <iron/data/Data.h>
#endif
#ifndef INCLUDED_iron_object_CameraObject
#include <iron/object/CameraObject.h>
#endif
#ifndef INCLUDED_iron_object_Object
#include <iron/object/Object.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_00d47effb90d1cd2_8_new,"armory.logicnode.SetCameraFovNode","new",0x2396cd3c,"armory.logicnode.SetCameraFovNode.new","armory/logicnode/SetCameraFovNode.hx",8,0x4e0893b2)
HX_LOCAL_STACK_FRAME(_hx_pos_00d47effb90d1cd2_11_run,"armory.logicnode.SetCameraFovNode","run",0x2399e427,"armory.logicnode.SetCameraFovNode.run","armory/logicnode/SetCameraFovNode.hx",11,0x4e0893b2)
namespace armory{
namespace logicnode{

void SetCameraFovNode_obj::__construct( ::armory::logicnode::LogicTree tree){
            	HX_STACKFRAME(&_hx_pos_00d47effb90d1cd2_8_new)
HXDLIN(   8)		super::__construct(tree);
            	}

Dynamic SetCameraFovNode_obj::__CreateEmpty() { return new SetCameraFovNode_obj; }

void *SetCameraFovNode_obj::_hx_vtable = 0;

Dynamic SetCameraFovNode_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< SetCameraFovNode_obj > _hx_result = new SetCameraFovNode_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool SetCameraFovNode_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x2e933162) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x2e933162;
	} else {
		return inClassId==(int)0x765627ae;
	}
}

void SetCameraFovNode_obj::run(){
            	HX_STACKFRAME(&_hx_pos_00d47effb90d1cd2_11_run)
HXLINE(  12)		 ::iron::object::CameraObject camera = ( ( ::iron::object::CameraObject)(this->inputs->__get((int)1).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  13)		Float fov = ( (Float)(this->inputs->__get((int)2).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  15)		if (hx::IsNull( camera )) {
HXLINE(  15)			return;
            		}
HXLINE(  17)		camera->data->raw->__SetField(HX_("fov",0d,c7,4d,00),fov,hx::paccDynamic);
HXLINE(  18)		camera->buildProjection();
HXLINE(  20)		this->super::run();
            	}



hx::ObjectPtr< SetCameraFovNode_obj > SetCameraFovNode_obj::__new( ::armory::logicnode::LogicTree tree) {
	hx::ObjectPtr< SetCameraFovNode_obj > __this = new SetCameraFovNode_obj();
	__this->__construct(tree);
	return __this;
}

hx::ObjectPtr< SetCameraFovNode_obj > SetCameraFovNode_obj::__alloc(hx::Ctx *_hx_ctx, ::armory::logicnode::LogicTree tree) {
	SetCameraFovNode_obj *__this = (SetCameraFovNode_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(SetCameraFovNode_obj), true, "armory.logicnode.SetCameraFovNode"));
	*(void **)__this = SetCameraFovNode_obj::_hx_vtable;
	__this->__construct(tree);
	return __this;
}

SetCameraFovNode_obj::SetCameraFovNode_obj()
{
}

hx::Val SetCameraFovNode_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { return hx::Val( run_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *SetCameraFovNode_obj_sMemberStorageInfo = 0;
static hx::StaticInfo *SetCameraFovNode_obj_sStaticStorageInfo = 0;
#endif

static ::String SetCameraFovNode_obj_sMemberFields[] = {
	HX_HCSTRING("run","\x4b","\xe7","\x56","\x00"),
	::String(null()) };

static void SetCameraFovNode_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(SetCameraFovNode_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void SetCameraFovNode_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(SetCameraFovNode_obj::__mClass,"__mClass");
};

#endif

hx::Class SetCameraFovNode_obj::__mClass;

void SetCameraFovNode_obj::__register()
{
	hx::Object *dummy = new SetCameraFovNode_obj;
	SetCameraFovNode_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("armory.logicnode.SetCameraFovNode","\x4a","\xbf","\x68","\x8c");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = SetCameraFovNode_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(SetCameraFovNode_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< SetCameraFovNode_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = SetCameraFovNode_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = SetCameraFovNode_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = SetCameraFovNode_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace armory
} // end namespace logicnode
