// Generated by Haxe 3.4.4
#include <hxcpp.h>

#ifndef INCLUDED_armory_logicnode_LogicNode
#include <armory/logicnode/LogicNode.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicNodeInput
#include <armory/logicnode/LogicNodeInput.h>
#endif
#ifndef INCLUDED_armory_logicnode_LogicTree
#include <armory/logicnode/LogicTree.h>
#endif
#ifndef INCLUDED_armory_logicnode_SetMeshNode
#include <armory/logicnode/SetMeshNode.h>
#endif
#ifndef INCLUDED_iron_Trait
#include <iron/Trait.h>
#endif
#ifndef INCLUDED_iron_data_Data
#include <iron/data/Data.h>
#endif
#ifndef INCLUDED_iron_data_MeshData
#include <iron/data/MeshData.h>
#endif
#ifndef INCLUDED_iron_object_MeshObject
#include <iron/object/MeshObject.h>
#endif
#ifndef INCLUDED_iron_object_Object
#include <iron/object/Object.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_e6fa7b7a7c737c67_9_new,"armory.logicnode.SetMeshNode","new",0x38debf41,"armory.logicnode.SetMeshNode.new","armory/logicnode/SetMeshNode.hx",9,0xf3377e11)
HX_LOCAL_STACK_FRAME(_hx_pos_e6fa7b7a7c737c67_12_run,"armory.logicnode.SetMeshNode","run",0x38e1d62c,"armory.logicnode.SetMeshNode.run","armory/logicnode/SetMeshNode.hx",12,0xf3377e11)
namespace armory{
namespace logicnode{

void SetMeshNode_obj::__construct( ::armory::logicnode::LogicTree tree){
            	HX_STACKFRAME(&_hx_pos_e6fa7b7a7c737c67_9_new)
HXDLIN(   9)		super::__construct(tree);
            	}

Dynamic SetMeshNode_obj::__CreateEmpty() { return new SetMeshNode_obj; }

void *SetMeshNode_obj::_hx_vtable = 0;

Dynamic SetMeshNode_obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< SetMeshNode_obj > _hx_result = new SetMeshNode_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool SetMeshNode_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x05cacb17) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x05cacb17;
	} else {
		return inClassId==(int)0x2e933162;
	}
}

void SetMeshNode_obj::run(){
            	HX_STACKFRAME(&_hx_pos_e6fa7b7a7c737c67_12_run)
HXLINE(  13)		 ::iron::object::MeshObject object = ( ( ::iron::object::MeshObject)(this->inputs->__get((int)1).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  14)		 ::iron::data::MeshData mesh = ( ( ::iron::data::MeshData)(this->inputs->__get((int)2).StaticCast<  ::armory::logicnode::LogicNodeInput >()->get()) );
HXLINE(  16)		if (hx::IsNull( object )) {
HXLINE(  16)			return;
            		}
HXLINE(  18)		object->data = mesh;
HXLINE(  20)		this->super::run();
            	}



hx::ObjectPtr< SetMeshNode_obj > SetMeshNode_obj::__new( ::armory::logicnode::LogicTree tree) {
	hx::ObjectPtr< SetMeshNode_obj > __this = new SetMeshNode_obj();
	__this->__construct(tree);
	return __this;
}

hx::ObjectPtr< SetMeshNode_obj > SetMeshNode_obj::__alloc(hx::Ctx *_hx_ctx, ::armory::logicnode::LogicTree tree) {
	SetMeshNode_obj *__this = (SetMeshNode_obj*)(hx::Ctx::alloc(_hx_ctx, sizeof(SetMeshNode_obj), true, "armory.logicnode.SetMeshNode"));
	*(void **)__this = SetMeshNode_obj::_hx_vtable;
	__this->__construct(tree);
	return __this;
}

SetMeshNode_obj::SetMeshNode_obj()
{
}

hx::Val SetMeshNode_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"run") ) { return hx::Val( run_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *SetMeshNode_obj_sMemberStorageInfo = 0;
static hx::StaticInfo *SetMeshNode_obj_sStaticStorageInfo = 0;
#endif

static ::String SetMeshNode_obj_sMemberFields[] = {
	HX_HCSTRING("run","\x4b","\xe7","\x56","\x00"),
	::String(null()) };

static void SetMeshNode_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(SetMeshNode_obj::__mClass,"__mClass");
};

#ifdef HXCPP_VISIT_ALLOCS
static void SetMeshNode_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(SetMeshNode_obj::__mClass,"__mClass");
};

#endif

hx::Class SetMeshNode_obj::__mClass;

void SetMeshNode_obj::__register()
{
	hx::Object *dummy = new SetMeshNode_obj;
	SetMeshNode_obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("armory.logicnode.SetMeshNode","\xcf","\x0a","\x64","\xe6");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = SetMeshNode_obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = hx::Class_obj::dupFunctions(SetMeshNode_obj_sMemberFields);
	__mClass->mCanCast = hx::TCanCast< SetMeshNode_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = SetMeshNode_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = SetMeshNode_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = SetMeshNode_obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace armory
} // end namespace logicnode
