// Generated by Haxe 3.4.4
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_kha__Color_Color_Impl_
#include <kha/_Color/Color_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_33_fromValue,"kha._Color.Color_Impl_","fromValue",0xdaee86bc,"kha._Color.Color_Impl_.fromValue","kha/Color.hx",33,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_40_fromBytes,"kha._Color.Color_Impl_","fromBytes",0x66ce0fb6,"kha._Color.Color_Impl_.fromBytes","kha/Color.hx",40,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_47_fromFloats,"kha._Color.Color_Impl_","fromFloats",0xa7667dac,"kha._Color.Color_Impl_.fromFloats","kha/Color.hx",47,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_54_fromString,"kha._Color.Color_Impl_","fromString",0x77408326,"kha._Color.Color_Impl_.fromString","kha/Color.hx",54,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_99__new,"kha._Color.Color_Impl_","_new",0x1251106c,"kha._Color.Color_Impl_._new","kha/Color.hx",99,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_109_get_value,"kha._Color.Color_Impl_","get_value",0x6a0ef8dd,"kha._Color.Color_Impl_.get_value","kha/Color.hx",109,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_112_set_value,"kha._Color.Color_Impl_","set_value",0x4d5fe4e9,"kha._Color.Color_Impl_.set_value","kha/Color.hx",112,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_118_get_Rb,"kha._Color.Color_Impl_","get_Rb",0x231ef2e4,"kha._Color.Color_Impl_.get_Rb","kha/Color.hx",118,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_122_get_Gb,"kha._Color.Color_Impl_","get_Gb",0x231ee94f,"kha._Color.Color_Impl_.get_Gb","kha/Color.hx",122,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_126_get_Bb,"kha._Color.Color_Impl_","get_Bb",0x231ee4f4,"kha._Color.Color_Impl_.get_Bb","kha/Color.hx",126,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_130_get_Ab,"kha._Color.Color_Impl_","get_Ab",0x231ee415,"kha._Color.Color_Impl_.get_Ab","kha/Color.hx",130,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_133_set_Rb,"kha._Color.Color_Impl_","set_Rb",0xef674758,"kha._Color.Color_Impl_.set_Rb","kha/Color.hx",133,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_138_set_Gb,"kha._Color.Color_Impl_","set_Gb",0xef673dc3,"kha._Color.Color_Impl_.set_Gb","kha/Color.hx",138,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_143_set_Bb,"kha._Color.Color_Impl_","set_Bb",0xef673968,"kha._Color.Color_Impl_.set_Bb","kha/Color.hx",143,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_148_set_Ab,"kha._Color.Color_Impl_","set_Ab",0xef673889,"kha._Color.Color_Impl_.set_Ab","kha/Color.hx",148,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_154_get_R,"kha._Color.Color_Impl_","get_R",0x89ea53be,"kha._Color.Color_Impl_.get_R","kha/Color.hx",154,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_158_get_G,"kha._Color.Color_Impl_","get_G",0x89ea53b3,"kha._Color.Color_Impl_.get_G","kha/Color.hx",158,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_162_get_B,"kha._Color.Color_Impl_","get_B",0x89ea53ae,"kha._Color.Color_Impl_.get_B","kha/Color.hx",162,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_166_get_A,"kha._Color.Color_Impl_","get_A",0x89ea53ad,"kha._Color.Color_Impl_.get_A","kha/Color.hx",166,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_169_set_R,"kha._Color.Color_Impl_","set_R",0x72b949ca,"kha._Color.Color_Impl_.set_R","kha/Color.hx",169,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_174_set_G,"kha._Color.Color_Impl_","set_G",0x72b949bf,"kha._Color.Color_Impl_.set_G","kha/Color.hx",174,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_179_set_B,"kha._Color.Color_Impl_","set_B",0x72b949ba,"kha._Color.Color_Impl_.set_B","kha/Color.hx",179,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_184_set_A,"kha._Color.Color_Impl_","set_A",0x72b949b9,"kha._Color.Color_Impl_.set_A","kha/Color.hx",184,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_13_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",13,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_14_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",14,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_15_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",15,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_16_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",16,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_17_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",17,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_18_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",18,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_19_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",19,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_20_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",20,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_21_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",21,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_22_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",22,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_23_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",23,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_25_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",25,0xcf6d63e6)
HX_LOCAL_STACK_FRAME(_hx_pos_d2f5d32ec190c5d3_27_boot,"kha._Color.Color_Impl_","boot",0x144d7f3d,"kha._Color.Color_Impl_.boot","kha/Color.hx",27,0xcf6d63e6)
namespace kha{
namespace _Color{

void Color_Impl__obj::__construct() { }

Dynamic Color_Impl__obj::__CreateEmpty() { return new Color_Impl__obj; }

void *Color_Impl__obj::_hx_vtable = 0;

Dynamic Color_Impl__obj::__Create(hx::DynamicArray inArgs)
{
	hx::ObjectPtr< Color_Impl__obj > _hx_result = new Color_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Color_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x21d3075f;
}

int Color_Impl__obj::Black;

int Color_Impl__obj::White;

int Color_Impl__obj::Red;

int Color_Impl__obj::Blue;

int Color_Impl__obj::Green;

int Color_Impl__obj::Magenta;

int Color_Impl__obj::Yellow;

int Color_Impl__obj::Cyan;

int Color_Impl__obj::Purple;

int Color_Impl__obj::Pink;

int Color_Impl__obj::Orange;

int Color_Impl__obj::Transparent;

float Color_Impl__obj::invMaxChannelValue;

int Color_Impl__obj::fromValue(int value){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_33_fromValue)
HXDLIN(  33)		return ::kha::_Color::Color_Impl__obj::_new(value);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,fromValue,return )

int Color_Impl__obj::fromBytes(int r,int g,int b,hx::Null< int >  __o_a){
int a = __o_a.Default(255);
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_40_fromBytes)
HXDLIN(  40)		return ::kha::_Color::Color_Impl__obj::_new(((int)((int)((int)((int)a << (int)(int)24) | (int)((int)r << (int)(int)16)) | (int)((int)g << (int)(int)8)) | (int)b));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC4(Color_Impl__obj,fromBytes,return )

int Color_Impl__obj::fromFloats(float r,float g,float b,hx::Null< float >  __o_a){
float a = __o_a.Default(1);
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_47_fromFloats)
HXDLIN(  47)		int _hx_tmp = ((int)::Std_obj::_hx_int((a * (int)255)) << (int)(int)24);
HXDLIN(  47)		int _hx_tmp1 = ((int)_hx_tmp | (int)((int)::Std_obj::_hx_int((r * (int)255)) << (int)(int)16));
HXDLIN(  47)		int _hx_tmp2 = ((int)_hx_tmp1 | (int)((int)::Std_obj::_hx_int((g * (int)255)) << (int)(int)8));
HXDLIN(  47)		return ::kha::_Color::Color_Impl__obj::_new(((int)_hx_tmp2 | (int)::Std_obj::_hx_int((b * (int)255))));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC4(Color_Impl__obj,fromFloats,return )

int Color_Impl__obj::fromString(::String value){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_54_fromString)
HXDLIN(  54)		bool _hx_tmp;
HXDLIN(  54)		bool _hx_tmp1;
HXDLIN(  54)		if ((value.length != (int)7)) {
HXDLIN(  54)			_hx_tmp1 = (value.length == (int)9);
            		}
            		else {
HXDLIN(  54)			_hx_tmp1 = true;
            		}
HXDLIN(  54)		if (_hx_tmp1) {
HXDLIN(  54)			_hx_tmp = (value.cca((int)0) == (int)35);
            		}
            		else {
HXDLIN(  54)			_hx_tmp = false;
            		}
HXDLIN(  54)		if (_hx_tmp) {
HXLINE(  55)			 ::Dynamic colorValue = ::Std_obj::parseInt((HX_("0x",48,2a,00,00) + value.substr((int)1,null())));
HXLINE(  56)			if ((value.length == (int)7)) {
HXLINE(  57)				colorValue = (colorValue + (int)-16777216);
            			}
HXLINE(  59)			return ::kha::_Color::Color_Impl__obj::_new(colorValue);
            		}
            		else {
HXLINE(  62)			HX_STACK_DO_THROW(((HX_("Invalid Color string: '",2a,42,44,dd) + value) + HX_("'",27,00,00,00)));
            		}
HXLINE(  54)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,fromString,return )

int Color_Impl__obj::_new(int value){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_99__new)
HXDLIN(  99)		int this1 = value;
HXDLIN(  99)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,_new,return )

int Color_Impl__obj::get_value(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_109_get_value)
HXDLIN( 109)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_value,return )

int Color_Impl__obj::set_value(int this1,int value){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_112_set_value)
HXLINE( 113)		this1 = value;
HXLINE( 114)		return this1;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_value,return )

int Color_Impl__obj::get_Rb(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_118_get_Rb)
HXDLIN( 118)		return hx::UShr(((int)this1 & (int)(int)16711680),(int)16);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_Rb,return )

int Color_Impl__obj::get_Gb(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_122_get_Gb)
HXDLIN( 122)		return hx::UShr(((int)this1 & (int)(int)65280),(int)8);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_Gb,return )

int Color_Impl__obj::get_Bb(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_126_get_Bb)
HXDLIN( 126)		return ((int)this1 & (int)(int)255);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_Bb,return )

int Color_Impl__obj::get_Ab(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_130_get_Ab)
HXDLIN( 130)		return hx::UShr(this1,(int)24);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_Ab,return )

int Color_Impl__obj::set_Rb(int this1,int i){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_133_set_Rb)
HXLINE( 134)		this1 = ((int)((int)((int)((int)hx::UShr(this1,(int)24) << (int)(int)24) | (int)((int)i << (int)(int)16)) | (int)((int)hx::UShr(((int)this1 & (int)(int)65280),(int)8) << (int)(int)8)) | (int)((int)this1 & (int)(int)255));
HXLINE( 135)		return i;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_Rb,return )

int Color_Impl__obj::set_Gb(int this1,int i){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_138_set_Gb)
HXLINE( 139)		this1 = ((int)((int)((int)((int)hx::UShr(this1,(int)24) << (int)(int)24) | (int)((int)hx::UShr(((int)this1 & (int)(int)16711680),(int)16) << (int)(int)16)) | (int)((int)i << (int)(int)8)) | (int)((int)this1 & (int)(int)255));
HXLINE( 140)		return i;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_Gb,return )

int Color_Impl__obj::set_Bb(int this1,int i){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_143_set_Bb)
HXLINE( 144)		this1 = ((int)((int)((int)((int)hx::UShr(this1,(int)24) << (int)(int)24) | (int)((int)hx::UShr(((int)this1 & (int)(int)16711680),(int)16) << (int)(int)16)) | (int)((int)hx::UShr(((int)this1 & (int)(int)65280),(int)8) << (int)(int)8)) | (int)i);
HXLINE( 145)		return i;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_Bb,return )

int Color_Impl__obj::set_Ab(int this1,int i){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_148_set_Ab)
HXLINE( 149)		this1 = ((int)((int)((int)((int)i << (int)(int)24) | (int)((int)hx::UShr(((int)this1 & (int)(int)16711680),(int)16) << (int)(int)16)) | (int)((int)hx::UShr(((int)this1 & (int)(int)65280),(int)8) << (int)(int)8)) | (int)((int)this1 & (int)(int)255));
HXLINE( 150)		return i;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_Ab,return )

float Color_Impl__obj::get_R(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_154_get_R)
HXDLIN( 154)		return (hx::UShr(((int)this1 & (int)(int)16711680),(int)16) * ((Float)0.00392156862745098));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_R,return )

float Color_Impl__obj::get_G(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_158_get_G)
HXDLIN( 158)		return (hx::UShr(((int)this1 & (int)(int)65280),(int)8) * ((Float)0.00392156862745098));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_G,return )

float Color_Impl__obj::get_B(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_162_get_B)
HXDLIN( 162)		return (((int)this1 & (int)(int)255) * ((Float)0.00392156862745098));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_B,return )

float Color_Impl__obj::get_A(int this1){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_166_get_A)
HXDLIN( 166)		return (hx::UShr(this1,(int)24) * ((Float)0.00392156862745098));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Color_Impl__obj,get_A,return )

float Color_Impl__obj::set_R(int this1,float f){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_169_set_R)
HXLINE( 170)		int this2 = ((int)::Std_obj::_hx_int(((hx::UShr(this1,(int)24) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)24);
HXDLIN( 170)		int this3 = ((int)this2 | (int)((int)::Std_obj::_hx_int((f * (int)255)) << (int)(int)16));
HXDLIN( 170)		int this4 = ((int)this3 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)65280),(int)8) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)8));
HXDLIN( 170)		this1 = ((int)this4 | (int)::Std_obj::_hx_int(((((int)this1 & (int)(int)255) * ((Float)0.00392156862745098)) * (int)255)));
HXLINE( 171)		return f;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_R,return )

float Color_Impl__obj::set_G(int this1,float f){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_174_set_G)
HXLINE( 175)		int this2 = ((int)::Std_obj::_hx_int(((hx::UShr(this1,(int)24) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)24);
HXDLIN( 175)		int this3 = ((int)this2 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)16711680),(int)16) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)16));
HXDLIN( 175)		int this4 = ((int)this3 | (int)((int)::Std_obj::_hx_int((f * (int)255)) << (int)(int)8));
HXDLIN( 175)		this1 = ((int)this4 | (int)::Std_obj::_hx_int(((((int)this1 & (int)(int)255) * ((Float)0.00392156862745098)) * (int)255)));
HXLINE( 176)		return f;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_G,return )

float Color_Impl__obj::set_B(int this1,float f){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_179_set_B)
HXLINE( 180)		int this2 = ((int)::Std_obj::_hx_int(((hx::UShr(this1,(int)24) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)24);
HXDLIN( 180)		int this3 = ((int)this2 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)16711680),(int)16) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)16));
HXDLIN( 180)		int this4 = ((int)this3 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)65280),(int)8) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)8));
HXDLIN( 180)		this1 = ((int)this4 | (int)::Std_obj::_hx_int((f * (int)255)));
HXLINE( 181)		return f;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_B,return )

float Color_Impl__obj::set_A(int this1,float f){
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_184_set_A)
HXLINE( 185)		int this2 = ((int)::Std_obj::_hx_int((f * (int)255)) << (int)(int)24);
HXDLIN( 185)		int this3 = ((int)this2 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)16711680),(int)16) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)16));
HXDLIN( 185)		int this4 = ((int)this3 | (int)((int)::Std_obj::_hx_int(((hx::UShr(((int)this1 & (int)(int)65280),(int)8) * ((Float)0.00392156862745098)) * (int)255)) << (int)(int)8));
HXDLIN( 185)		this1 = ((int)this4 | (int)::Std_obj::_hx_int(((((int)this1 & (int)(int)255) * ((Float)0.00392156862745098)) * (int)255)));
HXLINE( 186)		return f;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(Color_Impl__obj,set_A,return )


Color_Impl__obj::Color_Impl__obj()
{
}

bool Color_Impl__obj::__GetStatic(const ::String &inName, Dynamic &outValue, hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_new") ) { outValue = _new_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"get_R") ) { outValue = get_R_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_G") ) { outValue = get_G_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_B") ) { outValue = get_B_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_A") ) { outValue = get_A_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_R") ) { outValue = set_R_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_G") ) { outValue = set_G_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_B") ) { outValue = set_B_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_A") ) { outValue = set_A_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"get_Rb") ) { outValue = get_Rb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_Gb") ) { outValue = get_Gb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_Bb") ) { outValue = get_Bb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_Ab") ) { outValue = get_Ab_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_Rb") ) { outValue = set_Rb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_Gb") ) { outValue = set_Gb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_Bb") ) { outValue = set_Bb_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_Ab") ) { outValue = set_Ab_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"fromValue") ) { outValue = fromValue_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"fromBytes") ) { outValue = fromBytes_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"get_value") ) { outValue = get_value_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set_value") ) { outValue = set_value_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"fromFloats") ) { outValue = fromFloats_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"fromString") ) { outValue = fromString_dyn(); return true; }
	}
	return false;
}

#if HXCPP_SCRIPTABLE
static hx::StorageInfo *Color_Impl__obj_sMemberStorageInfo = 0;
static hx::StaticInfo Color_Impl__obj_sStaticStorageInfo[] = {
	{hx::fsInt,(void *) &Color_Impl__obj::Black,HX_HCSTRING("Black","\x9f","\x45","\x1f","\x48")},
	{hx::fsInt,(void *) &Color_Impl__obj::White,HX_HCSTRING("White","\x89","\xba","\xea","\x5c")},
	{hx::fsInt,(void *) &Color_Impl__obj::Red,HX_HCSTRING("Red","\x31","\x91","\x3e","\x00")},
	{hx::fsInt,(void *) &Color_Impl__obj::Blue,HX_HCSTRING("Blue","\xba","\x6e","\xf2","\x2b")},
	{hx::fsInt,(void *) &Color_Impl__obj::Green,HX_HCSTRING("Green","\xa3","\x7e","\x1a","\x2d")},
	{hx::fsInt,(void *) &Color_Impl__obj::Magenta,HX_HCSTRING("Magenta","\x09","\xe2","\xee","\xdb")},
	{hx::fsInt,(void *) &Color_Impl__obj::Yellow,HX_HCSTRING("Yellow","\x94","\x13","\xf1","\x04")},
	{hx::fsInt,(void *) &Color_Impl__obj::Cyan,HX_HCSTRING("Cyan","\x43","\x71","\xa5","\x2c")},
	{hx::fsInt,(void *) &Color_Impl__obj::Purple,HX_HCSTRING("Purple","\x5c","\x6a","\x1e","\xa6")},
	{hx::fsInt,(void *) &Color_Impl__obj::Pink,HX_HCSTRING("Pink","\x96","\x1e","\x31","\x35")},
	{hx::fsInt,(void *) &Color_Impl__obj::Orange,HX_HCSTRING("Orange","\x0e","\x27","\x51","\x7a")},
	{hx::fsInt,(void *) &Color_Impl__obj::Transparent,HX_HCSTRING("Transparent","\x32","\xc3","\xec","\x06")},
	{hx::fsObject /*::cpp::Float32*/ ,(void *) &Color_Impl__obj::invMaxChannelValue,HX_HCSTRING("invMaxChannelValue","\x81","\x3a","\x08","\xe4")},
	{ hx::fsUnknown, 0, null()}
};
#endif

static void Color_Impl__obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Color_Impl__obj::__mClass,"__mClass");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Black,"Black");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::White,"White");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Red,"Red");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Blue,"Blue");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Green,"Green");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Magenta,"Magenta");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Yellow,"Yellow");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Cyan,"Cyan");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Purple,"Purple");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Pink,"Pink");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Orange,"Orange");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::Transparent,"Transparent");
	HX_MARK_MEMBER_NAME(Color_Impl__obj::invMaxChannelValue,"invMaxChannelValue");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Color_Impl__obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::__mClass,"__mClass");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Black,"Black");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::White,"White");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Red,"Red");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Blue,"Blue");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Green,"Green");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Magenta,"Magenta");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Yellow,"Yellow");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Cyan,"Cyan");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Purple,"Purple");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Pink,"Pink");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Orange,"Orange");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::Transparent,"Transparent");
	HX_VISIT_MEMBER_NAME(Color_Impl__obj::invMaxChannelValue,"invMaxChannelValue");
};

#endif

hx::Class Color_Impl__obj::__mClass;

static ::String Color_Impl__obj_sStaticFields[] = {
	HX_HCSTRING("Black","\x9f","\x45","\x1f","\x48"),
	HX_HCSTRING("White","\x89","\xba","\xea","\x5c"),
	HX_HCSTRING("Red","\x31","\x91","\x3e","\x00"),
	HX_HCSTRING("Blue","\xba","\x6e","\xf2","\x2b"),
	HX_HCSTRING("Green","\xa3","\x7e","\x1a","\x2d"),
	HX_HCSTRING("Magenta","\x09","\xe2","\xee","\xdb"),
	HX_HCSTRING("Yellow","\x94","\x13","\xf1","\x04"),
	HX_HCSTRING("Cyan","\x43","\x71","\xa5","\x2c"),
	HX_HCSTRING("Purple","\x5c","\x6a","\x1e","\xa6"),
	HX_HCSTRING("Pink","\x96","\x1e","\x31","\x35"),
	HX_HCSTRING("Orange","\x0e","\x27","\x51","\x7a"),
	HX_HCSTRING("Transparent","\x32","\xc3","\xec","\x06"),
	HX_HCSTRING("invMaxChannelValue","\x81","\x3a","\x08","\xe4"),
	HX_HCSTRING("fromValue","\xa7","\x69","\x41","\xe6"),
	HX_HCSTRING("fromBytes","\xa1","\xf2","\x20","\x72"),
	HX_HCSTRING("fromFloats","\x61","\x28","\x9a","\x84"),
	HX_HCSTRING("fromString","\xdb","\x2d","\x74","\x54"),
	HX_HCSTRING("_new","\x61","\x15","\x1f","\x3f"),
	HX_HCSTRING("get_value","\xc8","\xdb","\x61","\x75"),
	HX_HCSTRING("set_value","\xd4","\xc7","\xb2","\x58"),
	HX_HCSTRING("get_Rb","\x19","\xdf","\x2f","\xa3"),
	HX_HCSTRING("get_Gb","\x84","\xd5","\x2f","\xa3"),
	HX_HCSTRING("get_Bb","\x29","\xd1","\x2f","\xa3"),
	HX_HCSTRING("get_Ab","\x4a","\xd0","\x2f","\xa3"),
	HX_HCSTRING("set_Rb","\x8d","\x33","\x78","\x6f"),
	HX_HCSTRING("set_Gb","\xf8","\x29","\x78","\x6f"),
	HX_HCSTRING("set_Bb","\x9d","\x25","\x78","\x6f"),
	HX_HCSTRING("set_Ab","\xbe","\x24","\x78","\x6f"),
	HX_HCSTRING("get_R","\x29","\xa5","\x60","\x91"),
	HX_HCSTRING("get_G","\x1e","\xa5","\x60","\x91"),
	HX_HCSTRING("get_B","\x19","\xa5","\x60","\x91"),
	HX_HCSTRING("get_A","\x18","\xa5","\x60","\x91"),
	HX_HCSTRING("set_R","\x35","\x9b","\x2f","\x7a"),
	HX_HCSTRING("set_G","\x2a","\x9b","\x2f","\x7a"),
	HX_HCSTRING("set_B","\x25","\x9b","\x2f","\x7a"),
	HX_HCSTRING("set_A","\x24","\x9b","\x2f","\x7a"),
	::String(null())
};

void Color_Impl__obj::__register()
{
	hx::Object *dummy = new Color_Impl__obj;
	Color_Impl__obj::_hx_vtable = *(void **)dummy;
	hx::Static(__mClass) = new hx::Class_obj();
	__mClass->mName = HX_HCSTRING("kha._Color.Color_Impl_","\x43","\x41","\x5a","\xbf");
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Color_Impl__obj::__GetStatic;
	__mClass->mSetStaticField = &hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = Color_Impl__obj_sMarkStatics;
	__mClass->mStatics = hx::Class_obj::dupFunctions(Color_Impl__obj_sStaticFields);
	__mClass->mMembers = hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = hx::TCanCast< Color_Impl__obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Color_Impl__obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Color_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Color_Impl__obj_sStaticStorageInfo;
#endif
	hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Color_Impl__obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_13_boot)
HXDLIN(  13)		Black = (int)-16777216;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_14_boot)
HXDLIN(  14)		White = (int)-1;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_15_boot)
HXDLIN(  15)		Red = (int)-65536;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_16_boot)
HXDLIN(  16)		Blue = (int)-16776961;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_17_boot)
HXDLIN(  17)		Green = (int)-16711936;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_18_boot)
HXDLIN(  18)		Magenta = (int)-65281;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_19_boot)
HXDLIN(  19)		Yellow = (int)-256;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_20_boot)
HXDLIN(  20)		Cyan = (int)-16711681;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_21_boot)
HXDLIN(  21)		Purple = (int)-8388480;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_22_boot)
HXDLIN(  22)		Pink = (int)-16181;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_23_boot)
HXDLIN(  23)		Orange = (int)-23296;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_25_boot)
HXDLIN(  25)		Transparent = (int)0;
            	}
{
            	HX_STACKFRAME(&_hx_pos_d2f5d32ec190c5d3_27_boot)
HXDLIN(  27)		invMaxChannelValue = ((Float)0.00392156862745098);
            	}
}

} // end namespace kha
} // end namespace _Color
