// Generated by Haxe 3.4.4
#ifndef INCLUDED_iron_math_Quat
#define INCLUDED_iron_math_Quat

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(iron,math,Mat4)
HX_DECLARE_CLASS2(iron,math,Quat)
HX_DECLARE_CLASS2(iron,math,Vec4)

namespace iron{
namespace math{


class HXCPP_CLASS_ATTRIBUTES Quat_obj : public hx::Object
{
	public:
		typedef hx::Object super;
		typedef Quat_obj OBJ_;
		Quat_obj();

	public:
		enum { _hx_ClassId = 0x1441ffeb };

		void __construct(hx::Null< Float >  __o_x,hx::Null< Float >  __o_y,hx::Null< Float >  __o_z,hx::Null< Float >  __o_w);
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="iron.math.Quat")
			{ return hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return hx::Object::operator new(inSize+extra,false,"iron.math.Quat"); }
		static hx::ObjectPtr< Quat_obj > __new(hx::Null< Float >  __o_x,hx::Null< Float >  __o_y,hx::Null< Float >  __o_z,hx::Null< Float >  __o_w);
		static hx::ObjectPtr< Quat_obj > __alloc(hx::Ctx *_hx_ctx,hx::Null< Float >  __o_x,hx::Null< Float >  __o_y,hx::Null< Float >  __o_z,hx::Null< Float >  __o_w);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(hx::DynamicArray inArgs);
		//~Quat_obj();

		HX_DO_RTTI_ALL;
		hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, hx::PropertyAccess inCallProp);
		hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_HCSTRING("Quat","\xf7","\x64","\xe3","\x35"); }

		static void __boot();
		static  ::iron::math::Vec4 helpVec0;
		static  ::iron::math::Vec4 helpVec1;
		static  ::iron::math::Vec4 helpVec2;
		static  ::iron::math::Quat identity();
		static ::Dynamic identity_dyn();

		static  ::iron::math::Quat lerp( ::iron::math::Quat q1, ::iron::math::Quat q2,float ratio);
		static ::Dynamic lerp_dyn();

		static  ::iron::math::Quat slerp( ::iron::math::Quat q1, ::iron::math::Quat q2,float v);
		static ::Dynamic slerp_dyn();

		float x;
		float y;
		float z;
		float w;
		void set(float x,float y,float z,float w);
		::Dynamic set_dyn();

		void fromAxisAngle( ::iron::math::Vec4 axis,float angle);
		::Dynamic fromAxisAngle_dyn();

		float toAxisAngle( ::iron::math::Vec4 axis);
		::Dynamic toAxisAngle_dyn();

		 ::iron::math::Quat fromRotationMat( ::iron::math::Mat4 m);
		::Dynamic fromRotationMat_dyn();

		void mult( ::iron::math::Quat q);
		::Dynamic mult_dyn();

		void multquats( ::iron::math::Quat q1, ::iron::math::Quat q2);
		::Dynamic multquats_dyn();

		void normalize();
		::Dynamic normalize_dyn();

		void setFrom( ::iron::math::Quat q);
		::Dynamic setFrom_dyn();

		 ::iron::math::Vec4 getEuler();
		::Dynamic getEuler_dyn();

		 ::iron::math::Quat fromEuler(float x,float y,float z);
		::Dynamic fromEuler_dyn();

		 ::iron::math::Mat4 toMat( ::iron::math::Mat4 m);
		::Dynamic toMat_dyn();

		float dot( ::iron::math::Quat q);
		::Dynamic dot_dyn();

		void fromTo( ::iron::math::Vec4 v1, ::iron::math::Vec4 v2);
		::Dynamic fromTo_dyn();

		virtual ::String toString();
		::Dynamic toString_dyn();

};

} // end namespace iron
} // end namespace math

#endif /* INCLUDED_iron_math_Quat */ 
